version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    ports:
      - 5000:5000
      - 5000:5000/udp
      - 4000:4000
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/noven_prod"
      MIX_ENV: prod
    restart: always
volumes:
  db-data:
