use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :noven, NovenWeb.Endpoint,
  secret_key_base: "OnFi2jrAAfmCc15upUIxUqFaVwJBOW/NGtQCFCqQJntgnYQIWVmrDZTPF5Vt453a",
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [host: "noven.app", port: 443],
  server: true,
  http: [
    port: 4000,
    transport_options: [socket_opts: [:inet6]]
  ]

# Do not print debug messages in production
config :logger, level: :info
config :logger, backends: [:console, RingLogger]

config :noven, Noven.Repo, pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")
